In [5]:
import pandas as pd
import numpy as np

PATH = r'C:\Users\Hege\Downloads\submissions_20231130.csv'
df = pd.read_csv(PATH)

In [16]:
df

,Submission-Date,name,email,Bestaetigung data,Bestaetigung image
0,2023-10-18 18:13:31,Julius Hege,julheg@gmx.de,1.0,1.0
1,2023-11-01 18:35:44,shahnaz,shahnazzjafarii@gmail.com,1.0,1.0
2,2023-11-01 18:46:11,Sarthak Parikh,sarthak.parikh@campus.lmu.de,1.0,1.0
3,2023-11-01 18:50:37,Sarthak,sarthak1682@gmail.com,1.0,1.0
4,2023-11-01 19:19:15,Philipp Scholl,Scholl@math.lmu.de,1.0,1.0
...,...,...,...,...,...
431,2023-11-29 17:25:25,Ali Oguz Can,alioguz.can@tum.de,1.0,1.0
432,2023-11-29 18:12:09,fazel ganji,fazel.ganji@gmail.com,1.0,1.0
433,2023-11-29 18:12:20,Simon Stürzebecher,simon.stuerzebecher@campus.lmu.de,1.0,1.0
434,2023-11-29 18:15:50,Ata Berk Çakır,ata.berk99@hotmail.com,1.0,1.0
435,2023-11-29 19:27:27,Fatima Amin,fatima.amin.bmes@gmail.com,1.0,1.0

In [14]:
emails = df['email'].values
def get_domain(email):
    # if not string make it string
    if type(email) != str:
        email = str(email)
    if '@' in email:
        domain = email.split('@')[1]
        # lower case
        domain = domain.lower()
        if '.' in domain:
            domain = '.'.join(domain.split('.')[-2:])
            return domain
email_domains = [get_domain(email) for email in emails]
email_domains = list(set(email_domains))

In [15]:
email_domains

['tum.de',
 'voltaro.de',
 'proniapredictors.eu',
 'yahoo.de',
 '163.com',
 'ai-agency.de',
 'acatech.de',
 'bmw.de',
 'gamil.com',
 'icloud.com',
 'me.com',
 'co.za',
 None,
 'web.de',
 'helmholtz-munich.de',
 'outlook.de',
 'nocodeailab.com',
 'ubefei.com',
 'uni-muenchen.de',
 'uni-munechen.de',
 'umcutrecht.nl',
 'pyucation.de',
 'lmu.de',
 'ifo.de',
 'hotmail.com',
 'gmail.com',
 'ife-project.com',
 'posteo.de',
 'onlinehome.de',
 'googlemail.com',
 'uni muenchen.de',
 'yahoo.com',
 'gmx.de',
 'psc-partners.com',
 'resultmc.de',
 'outlook.com',
 'rwth-aachen.de',
 'yahoo.fr',
 'santannapisa.it',
 't-online.de',
 'netic.de',
 'zohomail.eu',
 'campus.de',
 'sns.it',
 'ku.de',
 'uni-konstanz.de',
 'mpg.de',
 'hotmail.es']

In [28]:
institution_dict = {
    'lmu.de': 'Ludwig-Maximilians-Universität München',
    'tum.de': 'Technische Universität München',
    'ifo.de': 'ifo Institut',
    'uni-konstanz.de': 'Universität Konstanz',
    'bmw.de': 'BMW',
    'ai-agency.de': 'Baiosphere',
    'acatech.de': 'Acatech',
    'umcutrecht.nl': 'UMC Utrecht',
    'rwth-aachen.de': 'RWTH Aachen',
    'helmholtz-munich.de': 'Helmholtz Zentrum München',
    'mpg.de': 'Max-Planck-Gesellschaft',
    'ku.de': 'Katholische Universität Eichstätt-Ingolstadt',
}
# Deduplicate by name
df = df.drop_duplicates(subset=['name'])
# Give each person their institution
df['institution'] = df['email'].apply(lambda x: institution_dict.get(get_domain(x), np.nan))
# Drop people without institution
df_save = df.dropna(subset=['institution'])
# Save name and institution
save_path = r'C:\Users\Hege\Downloads\TeilnehmerSymposium.xlsx'
df_save[['name', 'institution']].to_excel(save_path, index=False)

In [29]:
# Count Other
df_save['institution'].value_counts()

Ludwig-Maximilians-Universität München          156
Technische Universität München                   19
Helmholtz Zentrum München                         3
Max-Planck-Gesellschaft                           2
BMW                                               2
ifo Institut                                      1
RWTH Aachen                                       1
Universität Konstanz                              1
Baiosphere                                        1
Katholische Universität Eichstätt-Ingolstadt      1
Acatech                                           1
UMC Utrecht                                       1
Name: institution, dtype: int64